### ISSUE TITLE
ModuleNotFoundError: No module named 'i2iTranslation'

### ISSUE THREAD

**Issue by genomicslf** [AI4SCR/VirtualMultiplexer#5]
Hi,I'm trying to deploy the project but encountered an error while training the model.
Traceback (most recent call last):
  File "C:\Users\VirtualMultiplexer\bin\main.py", line 5, in <module>
    from train import trainer
  File "C:\Users\VirtualMultiplexer\bin\train.py", line 6, in <module>
    from i2iTranslation.dataloader import ImagePatchDataset, TileDataset, prepare_image_patch_dataloader
ModuleNotFoundError: No module named 'i2iTranslation'
Could you please guide me on how to resolve this issue? 
Thank you!

**Comment by firstme2024** [comment]
Hello,can you solve this problem?
